apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: prod
type: Opaque
stringData:
  # The actual values will be replaced by kubectl command with environment variables
  AUTH_SECRET_KEY: "${AUTH_SECRET_KEY}"
  USERS_SECRET_KEY: "${USERS_SECRET_KEY}"
  POSTS_SECRET_KEY: "${POSTS_SECRET_KEY}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
stringData:
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_HOST: "${DB_HOST}" 